import { styles } from "../../Shared/Types/interface";

export interface createGroupStyle extends styles {
    boxShadow?:string,
    closeIconTint?:string,
    titleTextFont?: string,
    titleTextColor?: string,
    errorTextBackground?:string,
    errorTextBorderRadius?:string,
    errorTextBorder?:string,
    errorTextFont?: string,
    errorTextColor?: string,
    groupTypeTextFont?: string,
    groupTypeTextColor?: string,
    groupTypeTextBackground?:string,
    groupTypeBackground?:string,
    groupTypeTextActiveBackground?:string,
    groupTypeTextActiveBorderRadius?:string,
    groupTypeTextBoxShadow?:string,
    groupTypeTextBorderRadius?:string,
    groupTypeBorder?:string,
    nameTextFont?:string,
    nameTextColor?:string,
    groupTypeTextActiveBoxShadow?:string,
    namePlaceholderTextFont?:string,
    namePlaceholderTextColor?:string,
    nameInputBackground?:string,
    nameInputBorder?: string,
    nameInputBorderRadius?: string,
    nameInputBoxShadow?:string,
    passwordTextFont?:string,
    passwordTextColor?:string,
    passwordPlaceholderTextFont?:string,
    passwordPlaceholderTextColor?:string,
    passwordInputBackground?:string,
    passwordInputBorder?: string,
    passwordInputBorderRadius?: string,
    passwordInputBoxShadow?:string,
    createGroupButtonTextFont?:string,
    createGroupButtonTextColor?:string,
    createGroupButtonBackground?:string,
    createGroupButtonBorderRadius?:string,
}