#!/usr/bin/env bash
# =============================================================================
# Installs git hooks for this repository.
# Run once after cloning: npm run hooks:install
# =============================================================================

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPTS_DIR="$REPO_ROOT/scripts"

echo "Installing git hooks..."

# pre-commit
cat > "$HOOKS_DIR/pre-commit" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Edit scripts/pre-commit-checks.sh instead.
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec "$REPO_ROOT/scripts/pre-commit-checks.sh"
HOOK

chmod +x "$HOOKS_DIR/pre-commit"
chmod +x "$SCRIPTS_DIR/pre-commit-checks.sh"

echo "✓ pre-commit hook installed"
echo ""
echo "The hook will run automatically on every 'git commit'."
echo "To bypass in an emergency: git commit --no-verify"
